# Generated by Django 3.0.7 on 2020-06-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timer_start',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('open', 'Opened')], default='open', max_length=32),
        ),
    ]
