# Generated by Django 3.0.7 on 2020-06-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('finished', 'Finished'), ('in_process', 'In process')], default='in_process', max_length=32),
        ),
    ]
