# Generated by Django 3.0.7 on 2020-06-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0002_auto_20200630_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_process', 'In process'), ('finished', 'Finished')], default='in_process', max_length=32),
        ),
    ]
