# Generated by Django 3.0.7 on 2020-06-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0002_auto_20200624_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
