# Generated by Django 3.0.7 on 2020-06-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0002_auto_20200624_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
