# Generated by Django 3.0.7 on 2020-06-29 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TaskManager', '0002_auto_20200626_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Opened'), ('closed', 'Closed')], default='open', max_length=32),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(unique=True)),
                ('photo', models.ImageField(default='no_image.png', upload_to='project_image')),
                ('status', models.CharField(choices=[('in_process', 'In process'), ('finished', 'Finished')], default='open', max_length=32)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_project', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
