# Generated by Django 3.0.7 on 2020-06-29 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0003_auto_20200629_1546'),
        ('TaskManager', '0003_auto_20200629_1547'),
    ]

    operations = [
    ]
