# Generated by Django 3.0.7 on 2020-06-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0003_auto_20200630_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='exports',
            name='exp_info',
            field=models.CharField(default='', max_length=399),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('finished', 'Finished'), ('in_process', 'In process')], default='in_process', max_length=32),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('open', 'Opened'), ('closed', 'Closed')], default='open', max_length=32),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Opened'), ('closed', 'Closed')], default='open', max_length=32),
        ),
    ]
