# Generated by Django 3.0.7 on 2020-06-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0002_auto_20200624_1324'),
        ('TaskManager', '0003_task_time_start'),
    ]

    operations = [
    ]
