# Generated by Django 3.0.7 on 2020-06-29 11:03

import django.contrib.auth.models
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0003_auto_20200629_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='project',
            name='participants',
            field=multiselectfield.db.fields.MultiSelectField(max_length=100, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('finished', 'Finished'), ('in_process', 'In process')], default='in_process', max_length=32),
        ),
    ]
