# Generated by Django 3.0.7 on 2020-06-25 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0004_auto_20200625_0922'),
        ('TaskManager', '0004_auto_20200625_0852'),
    ]

    operations = [
    ]
