# Generated by Django 3.0.7 on 2020-06-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0005_auto_20200624_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_started',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('open', 'Opened')], default='open', max_length=32),
        ),
    ]
