# Generated by Django 3.0.7 on 2020-06-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0005_auto_20200629_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='participants',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Opened'), ('closed', 'Closed')], default='open', max_length=32),
        ),
    ]
