# Generated by Django 3.0.7 on 2020-06-30 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0005_auto_20200630_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('finished', 'Finished'), ('in_process', 'In process')], default='in_process', max_length=32),
        ),
        migrations.CreateModel(
            name='Subtasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_task', to='TaskManager.Task')),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask', to='TaskManager.Task')),
            ],
        ),
    ]
