# Generated by Django 3.0.7 on 2020-07-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0006_auto_20200630_1303'),
        ('TaskManager', '0006_auto_20200630_1441'),
    ]

    operations = [
    ]
