# Generated by Django 3.0.7 on 2020-06-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0007_auto_20200625_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelog',
            name='total_time',
        ),
        migrations.AddField(
            model_name='timelog',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
