# Generated by Django 3.0.7 on 2020-06-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0006_notification'),
        ('TaskManager', '0007_auto_20200623_1116'),
    ]

    operations = [
    ]
