# Generated by Django 3.0.7 on 2020-06-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0008_merge_20200623_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
