# Generated by Django 3.0.7 on 2020-07-01 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0008_auto_20200701_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='projecttask',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TaskManager.ProjectTask'),
        ),
        migrations.AlterField(
            model_name='like',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TaskManager.Task'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('finished', 'Finished'), ('in_process', 'In process')], default='in_process', max_length=32),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('open', 'Opened'), ('closed', 'Closed')], default='open', max_length=32),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Opened'), ('closed', 'Closed')], default='open', max_length=32),
        ),
    ]
