# Generated by Django 3.0.7 on 2020-07-01 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0009_auto_20200701_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='projecttask',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TaskManager.ProjectTask'),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TaskManager.Task'),
        ),
    ]
