# Generated by Django 3.0.7 on 2020-07-01 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0010_auto_20200701_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtasks',
            name='projectparent_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_task', to='TaskManager.ProjectTask'),
        ),
        migrations.AddField(
            model_name='subtasks',
            name='projectsubtask',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtask', to='TaskManager.ProjectTask'),
        ),
        migrations.AlterField(
            model_name='subtasks',
            name='parent_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_task', to='TaskManager.Task'),
        ),
        migrations.AlterField(
            model_name='subtasks',
            name='subtask',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtask', to='TaskManager.Task'),
        ),
    ]
